# -*- coding: utf-8 -*-
"""recommentation engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0_6zx-HPUpWzV8eB1cXYbzwmMHsdq_m
"""

!pip install -q sentence-transformers pandas numpy tabulate rich

from sentence_transformers import SentenceTransformer, util
import pandas as pd
import numpy as np
from tabulate import tabulate
from google.colab import files
import os
from datetime import datetime
import torch

print("📂 Upload alumni_profiles.csv, jobs.csv, and events.csv")
uploaded = files.upload()

profiles = pd.read_csv("alumni_profiles.csv")
jobs = pd.read_csv("jobs.csv")
events = pd.read_csv("events.csv")
for df in [profiles, jobs, events]:
    df.fillna("", inplace=True)

print("🧠 Loading model: hkunlp/instructor-large")
model = SentenceTransformer('hkunlp/instructor-large')

if torch.cuda.is_available():
    try:
        model = model.to('cuda')
        print("🚀 Using GPU acceleration")
    except RuntimeError:
        print("⚠️ GPU memory low, switching to CPU")
else:
    print("⚙️ Running on CPU")

def encode_texts(texts, instruction):
    sentences = [[instruction, text] for text in texts]
    return model.encode(sentences, convert_to_tensor=True, normalize_embeddings=True)

profiles["text"] = profiles["headline"] + " " + profiles["skills"] + " " + profiles["bio"]
jobs["text"] = jobs["title"] + " " + jobs["description"] + " " + jobs["company"]
events["text"] = events["name"] + " " + events["description"] + " " + events["tags"]

print("🔍 Encoding profiles, jobs, and events...")
profile_embeds = encode_texts(profiles["text"].tolist(), "Represent the alumni profile:")
job_embeds = encode_texts(jobs["text"].tolist(), "Represent the job posting:")
event_embeds = encode_texts(events["text"].tolist(), "Represent the alumni event:")

log_file = "user_interactions.csv"
if not os.path.exists(log_file):
    pd.DataFrame(columns=["timestamp","user_id","user_name","interaction_type","target","match_percent"]).to_csv(log_file, index=False)

def log_interaction(user_id, user_name, interaction_type, target, match_percent):
    df_log = pd.read_csv(log_file)
    entry = {"timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "user_id": user_id, "user_name": user_name,
             "interaction_type": interaction_type, "target": target, "match_percent": match_percent}
    df_log = pd.concat([df_log, pd.DataFrame([entry])], ignore_index=True)
    df_log.to_csv(log_file, index=False)

def show_match_bar(value):
    bar_length = int(value // 2)
    bar = "█" * bar_length + "░" * (50 - bar_length)
    return f"|{bar}| {value:.1f}%"

def recommend(user_id, rec_type="mentor", top_k=5):
    idx = profiles.index[profiles["id"].astype(str) == str(user_id)][0]
    user_embed = profile_embeds[idx]

    def tensor_to_numpy(t):
        return t.detach().cpu().numpy() if torch.is_tensor(t) else t

    if rec_type == "mentor":
        sims = util.cos_sim(user_embed, profile_embeds)[0]; sims[idx] = -1
        sims_cpu = tensor_to_numpy(sims)
        top_idx = sims_cpu.argsort()[::-1][:top_k]
        recs = profiles.iloc[top_idx][["name","headline","skills","graduationYear"]].copy()
        recs["Match %"] = (sims_cpu[top_idx] * 100).round(2)
        recs["Match Bar"] = recs["Match %"].apply(show_match_bar)
        return recs.reset_index(drop=True)
    elif rec_type == "job":
        sims = util.cos_sim(user_embed, job_embeds)[0]; sims_cpu = tensor_to_numpy(sims)
        top_idx = sims_cpu.argsort()[::-1][:top_k]
        recs = jobs.iloc[top_idx][["title","company","description","location"]].copy()
        recs["Match %"] = (sims_cpu[top_idx] * 100).round(2)
        recs["Match Bar"] = recs["Match %"].apply(show_match_bar)
        return recs.reset_index(drop=True)
    elif rec_type == "event":
        sims = util.cos_sim(user_embed, event_embeds)[0]; sims_cpu = tensor_to_numpy(sims)
        top_idx = sims_cpu.argsort()[::-1][:top_k]
        recs = events.iloc[top_idx][["name","description","location"]].copy()
        recs["Match %"] = (sims_cpu[top_idx] * 100).round(2)
        recs["Match Bar"] = recs["Match %"].apply(show_match_bar)
        return recs.reset_index(drop=True)

session_logs = []

while True:
    print("\n👤 Available Users:")
    print(tabulate(profiles.head(5)[['id','name','headline']], headers="keys", tablefmt="grid"))
    user_id = input("\nEnter user ID (1–50) or 'exit': ").strip()
    if user_id.lower() == "exit": break
    if user_id not in profiles["id"].astype(str).values:
        print("❌ Invalid ID."); continue
    user_name = profiles.loc[profiles["id"].astype(str)==user_id,"name"].values[0]
    print(f"\n🎓 Recommendations for: {user_name}\n")

    print("👥 Mentor Recommendations:")
    mentor_recs = recommend(user_id, "mentor")
    print(tabulate(mentor_recs[["name","headline","skills","Match Bar"]], headers="keys", tablefmt="grid", showindex=True))
    print("\n💼 Job Recommendations:")
    job_recs = recommend(user_id, "job")
    print(tabulate(job_recs[["title","company","location","Match Bar"]], headers="keys", tablefmt="grid", showindex=True))
    print("\n🎟️ Event Recommendations:")
    event_recs = recommend(user_id, "event")
    print(tabulate(event_recs[["name","location","Match Bar"]], headers="keys", tablefmt="grid", showindex=True))

    print("\n✨ Choose an action")
    print("1️⃣ Connect with a Mentor\n2️⃣ Apply for a Job\n3️⃣ Register for an Event\n4️⃣ Skip")
    choice = input("\nEnter your choice: ").strip()

    if choice == "1":
        idx = int(input("Enter mentor index: ")); s = mentor_recs.iloc[idx]
        print(f"\n✅ Connected with {s['name']} ({s['headline']}) – {s['Match %']}% match")
        log_interaction(user_id, user_name, "Connect Mentor", s['name'], s['Match %'])
        session_logs.append(["Connect Mentor", user_name, s['name'], s['Match %']])
    elif choice == "2":
        idx = int(input("Enter job index: ")); s = job_recs.iloc[idx]
        print(f"\n📤 Applied for {s['title']} at {s['company']} – {s['Match %']}% match")
        log_interaction(user_id, user_name, "Apply Job", s['title'], s['Match %'])
        session_logs.append(["Apply Job", user_name, s['title'], s['Match %']])
    elif choice == "3":
        idx = int(input("Enter event index: ")); s = event_recs.iloc[idx]
        print(f"\n🎫 Registered for {s['name']} ({s['location']}) – {s['Match %']}% match")
        log_interaction(user_id, user_name, "Register Event", s['name'], s['Match %'])
        session_logs.append(["Register Event", user_name, s['name'], s['Match %']])
    else:
        print("➡️ Skipped.")
    print("\n---------------------------------------------")

if session_logs:
    df = pd.DataFrame(session_logs, columns=["Interaction","User","Target","Match %"])
    print("\n📘 Session Summary\n")
    print(tabulate(df, headers="keys", tablefmt="grid", showindex=False))
    avg_match = np.mean([x[3] for x in session_logs])
    print(f"\n🧾 {len(df['User'].unique())} alumni tested | {len(df)} interactions | Avg Match: {avg_match:.2f}%")
else:
    print("\n📭 No interactions recorded.")